env:
  browser: true
  es6: true
  node: true
globals:
  $store: true
  describe: true
  it: true
extends: 'eslint:recommended'
plugins: ['html', 'vue']
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  no-console: 0
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
